<!DOCTYPE html>	
<html>
<head>
	<meta charset="utf-8">
	<title>
		Profile
	</title>
 <link rel="stylesheet" href="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />
  <script src="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.min.js"></script>
</head>

	<div class="row">
         <div class="input-group col-sm-10 col-sm-offset-1">
          <h1><font face="verdana"  size= "5.5" color="Gray"><b>Advanced search</b> </font> </h1>

	        <br>
	        <br></div></div>
	        <div class="row">
            <div class="input-group col-sm-10 col-sm-offset-1">
	  <span class="input-group-addon" id="basic-addon3">Title</span>
	  <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
	</div>
	</div>
	<br>
	 <div class="row">
     <div class="input-group col-sm-10 col-sm-offset-1">
	  <span class="input-group-addon" id="basic-addon3">Tags</span>
	  <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
	</div>
	</div>
	<br>
	 <div class="row">
            <div class="input-group col-sm-10 col-sm-offset-1">
	  <span class="input-group-addon" id="basic-addon3">Location</span>
	  <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
	</div></div>
	<br>      
		<div class="form-group row">
      <div class="input-group col-sm-10 col-sm-offset-1">
      <span class="input-group-addon" id="basic-addon3">Date</span>
        <input class="form-control" type="date" value="2017-01-01" id="example-date-input">
      </div>
    </div>
	<br>
	<div class= "row row-eq-height">
            <br>
  			<center><button type="button" class="btn btn-info" id="search-btn">Search</button></center>
  			<br><br>
     		</div><br>
     		<div class="row" id="main-row-search"></div>

 </html>